### ISSUE TITLE
getting an error when running "import vulners"

### ISSUE THREAD

**Issue by yonibudo** [vulnersCom/api#19]
hi

Im getting the below error when trying to import vulners:

Traceback (most recent call last):
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\gek0bccp.u5m.py", line 4, in <module>
    import vulners
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\lib\site-packages\vulners\__init__.py", line 5, in <module>
    from vulners.api import Vulners
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\lib\site-packages\vulners\api.py", line 26, in <module>
    class Vulners(object):
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\lib\site-packages\vulners\api.py", line 178, in Vulners
    @rate_limited(api_rate_limits)
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\lib\site-packages\vulners\common\ratelimit.py", line 101, in decorate
    LT.debug('DECORATE')
  File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Vulners_V7.0\lib\site-packages\vulners\common\ratelimit.py", line 80, in debug
    time.localtime(self.last_time_called.value)),
ValueError: Invalid format string

any idea why?

thank you

**Comment by MoodyMudit** [comment]
Facing the same issue.

**Comment by yonibudo** [comment]
> Facing the same issue.

found a temporary solution, just go to **api.py**

and replace **@rate_limited(**

with **#@rate_limited(**
 :)

**Comment by vulnersCom** [comment]
It's strange issue.
Please, share the environment.
Windows version, Python version.

**Comment by yonibudo** [comment]
The python version we are running is 2.7.14 running on windows server 2016.

**Comment by MoodyMudit** [comment]
I have windows server 2019 and python 2.7

**Comment by vulnersCom** [comment]
Fixed at: https://github.com/vulnersCom/api/releases/tag/1.5.2
