### ISSUE TITLE
Windows crashes on import due to localtime invalid format string

### ISSUE THREAD

**Issue by vesche** [vulnersCom/api#8]
OS: Win 2012 R2
Python: 2.7.15
Vulners API: 1.3.6 (latest)

```
C:\Users\Administrator\Desktop\api>python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vulners
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vulners\__init__.py", line 5, in <module>
    from vulners.api import Vulners
  File "vulners\api.py", line 22, in <module>
    class Vulners(object):
  File "vulners\api.py", line 126, in Vulners
    @rate_limited(api_rate_limits)
  File "vulners\common\ratelimit.py", line 101, in decorate
    LT.debug('DECORATE')
  File "vulners\common\ratelimit.py", line 80, in debug
    time.localtime(self.last_time_called.value)),
ValueError: Invalid format string
```

**Comment by danielguardicore** [comment]
This happens since 1.3.0, bug was introduced between 1.2.1 and 1.3

**Comment by yonibudo** [comment]
was this fixed? im having the same issue with the latest.
